# syntax=docker/dockerfile:1

# Here is an exemple of dockerfile using the Dockerfile base.
# Assuming you've built the base image using `docker build
# -t base-image:latest .`, here's how you can use it.

FROM base-image:latest

CMD [ "sample" ]