version: '3.9'

services:
  jenkins:
    privileged: true
    build:
      dockerfile: Jenkins/image/Dockerfile
      context: .
    restart: unless-stopped
    image: jenkins-image:jcasc
    ports:
      - '8081:8080'
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # UNIX socket to which the docker daemon is connected
    env_file:
     - .env
