jenkins:
  systemMessage: "Welcome to your Jenkins instance !"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: ${JENKINS_ADMIN_ID}
            permissions:
              - "Overall/Administer"
            entries:
              - user: ${JENKINS_ADMIN_ID}

credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            scope: GLOBAL
            id: github-ci-key
            username: Admin
            passphrase: ${GIT_SSH_KEY_PASSWORD}
            description: "SSH passphrase with private key file. Private key provided"
            privateKeySource:
              directEntry:
                privateKey: ${GIT_SSH_PRIVATE_KEY}

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"

jobs:
  - file: "/var/jenkins_home/scheduledBuildAndTest.groovy"